import { expect, test, describe } from "bun:test";
import { nameOf } from "../src/query.js";

/**
 * nameOf is a CROSS-IMPLEMENTATION contract, and it was not being treated as one.
 *
 * The Python port shipped a one-line stub — `title or description` — while this side
 * promoted slash commands, stripped compaction caveats and capped the length. So the
 * same session was called `/forward` by one reader and
 * `"<local-command-caveat>Caveat: The messages below were genera"` by the other, in
 * `sessions` as well as `pending`. Nothing failed; the two just disagreed.
 *
 * python/tests/test_name_of.py asserts these exact pairs. Change one, change both.
 */
const CASES: [string, { title?: string; description?: string }, string][] = [
  ["a real title wins outright",
   { title: "close-bank-sharding", description: "anything at all" }, "close-bank-sharding"],
  ["a blank title falls through to the description",
   { title: "   ", description: "fix the tokenizer" }, "fix the tokenizer"],
  ["a slash command is promoted over its XML",
   { description: "<command-name>/forward</command-name><command-args></command-args>" }, "/forward"],
  ["a slash command keeps its arguments",
   { description: "<command-name>/rrr</command-name><command-args> --light </command-args>" }, "/rrr --light"],
  ["an unterminated caveat block is dropped, not displayed",
   { description: "<local-command-caveat>Caveat: The messages below were generated by the user while" }, "(untitled)"],
  ["a bare caveat sentence is dropped too",
   { description: "Caveat: The messages below were generated by the user while running local commands" }, "(untitled)"],
  ["stray short tags are scrubbed to spaces",
   { description: "<system-reminder> index the vault </system-reminder>" }, "index the vault"],
  ["nothing usable is named, not left blank",
   { description: "" }, "(untitled)"],
];

describe("nameOf", () => {
  for (const [what, row, want] of CASES)
    test(what, () => expect(nameOf(row)).toBe(want));

  test("the result is capped at 70 characters", () => {
    // pending and sessions both print this inline; an uncapped description is a
    // 200-character row that wraps and destroys the column layout.
    expect(nameOf({ description: "x".repeat(300) }).length).toBe(70);
  });

  test("it takes the two fields, not a SessionRow", () => {
    // `pending` has a parsed transcript and no row — the whole point is that it is not
    // in the index. Widening the signature is what let both callers share one function.
    expect(nameOf({ title: "from a parse" })).toBe("from a parse");
  });
});
