import { expect, test, describe } from "bun:test";
import { nameOf } from "../src/query.js";

/**
 * nameOf is a CROSS-IMPLEMENTATION contract, and it was not being treated as one.
 *
 * The Python port shipped a one-line stub — `title or description` — while this side
 * promoted slash commands, stripped compaction caveats and capped the length. So the
 * same session was called `/forward` by one reader and
 * `"<local-command-caveat>Caveat: The messages below were genera"` by the other, in
 * `sessions` as well as `pending`. Nothing failed; the two just disagreed.
 *
 * python/tests/test_name_of.py asserts these exact pairs. Change one, change both.
 */
const CASES: [string, { title?: string; description?: string }, string][] = [
  ["a real title wins outright",
   { title: "close-bank-sharding", description: "anything at all" }, "close-bank-sharding"],
  ["a blank title falls through to the description",
   { title: "   ", description: "fix the tokenizer" }, "fix the tokenizer"],
  ["a slash command is promoted over its XML",
   { description: "<command-name>/forward</command-name><command-args></command-args>" }, "/forward"],
  ["a slash command keeps its arguments",
   { description: "<command-name>/rrr</command-name><command-args> --light </command-args>" }, "/rrr --light"],
  ["an unterminated caveat block is dropped, not displayed",
   { description: "<local-command-caveat>Caveat: The messages below were generated by the user while" }, "(untitled)"],
  ["a bare caveat sentence is dropped too",
   { description: "Caveat: The messages below were generated by the user while running local commands" }, "(untitled)"],
  ["stray short tags are scrubbed to spaces",
   { description: "<system-reminder> index the vault </system-reminder>" }, "index the vault"],
  ["a channel envelope of any length is not the name",
   { description: "<channel source=\"plugin:discord:discord\" chat_id=\"1512079809021214730\" message_id=\"1540006806481535127\" user=\"nazt_\" user_id=\"691531480689541170\" ts=\"2026-08-20T14:37:14.608Z\">can you check why the relay drops messages</channel>" }, "can you check why the relay drops messages"],
  ["a teammate envelope yields the message it carries",
   { description: "<teammate-message teammate_id=\"researcher\" color=\"blue\" summary=\"root cause found\">the uid collides on basename</teammate-message>" }, "the uid collides on basename"],
  ["an envelope cut off before its > is dropped whole",
   { description: "<channel source=\"plugin:discord:discord\" chat_id=\"1512079809021214730\" message_id=\"1540006806481535127\" user=\"nazt_\" user_id=\"691531480689541170\" ts=\"2026-08-20T14:37:14.608Z\" attachment_count=\"1\" att...[+412]" }, "(untitled)"],
  ["a truncation marker is not part of the name",
   { description: "<channel source=\"x\" chat_id=\"1\">hi there...[+500]" }, "hi there"],
  ["a channel turn in Thai keeps its Thai (#80)",
   { description: "<channel source=\"plugin:discord:discord\" chat_id=\"1512079809021214730\" user=\"nazt_\" ts=\"2026-09-13T00:08:06.936Z\">\nมีสอน 9:00 am\n</channel>" }, "มีสอน 9:00 am"],
  ["an unclosed channel envelope still yields the message (#80)",
   { description: "<channel source=\"plugin:discord:discord\" user=\"nazt_\">\nready?" }, "ready?"],
  ["a second channel envelope in the same turn is stripped too",
   { description: "<channel source=\"plugin:discord:discord\" chat_id=\"1512079809021214730\" user=\"nazt_\">ok</channel>\n<channel source=\"plugin:discord:discord\" chat_id=\"1512079809021214730\" user=\"nazt_\">ship it</channel>" }, "ok ship it"],
  ["a < in prose is not an envelope",
   { description: "why is a < b in this sort" }, "why is a < b in this sort"],
  ["nothing usable is named, not left blank",
   { description: "" }, "(untitled)"],
];

describe("nameOf", () => {
  for (const [what, row, want] of CASES)
    test(what, () => expect(nameOf(row)).toBe(want));

  test("the result is capped at 70 characters", () => {
    // pending and sessions both print this inline; an uncapped description is a
    // 200-character row that wraps and destroys the column layout.
    expect(nameOf({ description: "x".repeat(300) }).length).toBe(70);
  });

  test("it takes the two fields, not a SessionRow", () => {
    // `pending` has a parsed transcript and no row — the whole point is that it is not
    // in the index. Widening the signature is what let both callers share one function.
    expect(nameOf({ title: "from a parse" })).toBe("from a parse");
  });
});

describe("host preambles are not names", () => {
  /*
   * Measured over 1,750 codex sessions: 1,126 (64%) were named by injected text,
   * because only Claude's two shapes were recognised. The AGENTS.md blob alone is
   * 27,708 chars stored truncated to 200, so every one of those sessions showed the
   * same cut-off sentence differing only in a path.
   *
   * A FIFTH shape only became visible after the first four were skipped:
   * <environment_context> sits at user#2 and the real message at user#3, so each fix
   * uncovered the next. python/tests/test_name_of.py asserts the same list.
   */
  const PREAMBLES = [
    "# AGENTS.md instructions\n\n<INSTRUCTIONS>\n<!-- AUTONOMY DIRECTIVE -->",
    "# AGENTS.md instructions for /opt/Code/github.com/x/y",
    "<recommended_plugins> Here is a list of plugins that are available",
    "<codex_internal_context source=\"goal\"> Continue working towards",
    "<environment_context>\n  <cwd>/Users/beta</cwd>\n  <shell>zsh</shell>",
    "You have oh-my-codex installed. AGENTS.md is the orchestration brain",
  ];
  for (const p of PREAMBLES)
    test(`"${p.slice(0, 34).replace(/\n/g, " ")}…"`, () => expect(nameOf({ description: p })).toBe("(untitled)"));

  test("a title still wins over a preamble description", () => {
    expect(nameOf({ title: "real name", description: "<recommended_plugins> x" })).toBe("real name");
  });
  test("only a message that BEGINS as the directive is the directive", () => {
    // A human quoting the tag while debugging is a real message and keeps its name.
    expect(nameOf({ description: "why does <recommended_plugins> show up in my name?" }))
      .toBe("why does show up in my name?");
  });
  test("a pasted image tag is stripped, not left as the name", () => {
    // The {1,40} scrubber cannot reach it — an image tag carries a long path.
    expect(nameOf({ description: '<image name=[Image #1] path="/var/folders/41/x.png"> summarize the book' }))
      .toBe("summarize the book");
  });
  test("real messages are untouched, Thai included", () => {
    expect(nameOf({ description: "no i just you read thor memory /mcp" }))
      .toBe("no i just you read thor memory /mcp");
    expect(nameOf({ description: "[drdo-oracle] deploy เสร็จแล้ว + แก้ความเข้าใจผิด" }))
      .toBe("[drdo-oracle] deploy เสร็จแล้ว + แก้ความเข้าใจผิด");
  });
});
