"""nameOf is a cross-implementation contract. These are test/name-of.test.ts's cases.

The Python side shipped `title or description` while TypeScript promoted slash commands,
stripped compaction caveats and capped the length — so the same session was called
`/forward` by one reader and `"<local-command-caveat>Caveat: The messages below were
genera"` by the other, in `sessions` as well as `pending`. Nothing failed; they just
disagreed, which is the failure mode a second implementation exists to expose.
"""

import pytest

from relicpy.query import name_of

CASES = [
    ("a real title wins outright",
     {"title": "close-bank-sharding", "description": "anything at all"}, "close-bank-sharding"),
    ("a blank title falls through to the description",
     {"title": "   ", "description": "fix the tokenizer"}, "fix the tokenizer"),
    ("a slash command is promoted over its XML",
     {"description": "<command-name>/forward</command-name><command-args></command-args>"}, "/forward"),
    ("a slash command keeps its arguments",
     {"description": "<command-name>/rrr</command-name><command-args> --light </command-args>"}, "/rrr --light"),
    ("an unterminated caveat block is dropped, not displayed",
     {"description": "<local-command-caveat>Caveat: The messages below were generated by the user while"}, "(untitled)"),
    ("a bare caveat sentence is dropped too",
     {"description": "Caveat: The messages below were generated by the user while running local commands"}, "(untitled)"),
    ("stray short tags are scrubbed to spaces",
     {"description": "<system-reminder> index the vault </system-reminder>"}, "index the vault"),
    ("nothing usable is named, not left blank",
     {"description": ""}, "(untitled)"),
]


@pytest.mark.parametrize("what,row,want", CASES, ids=[c[0] for c in CASES])
def test_name_of(what, row, want):
    assert name_of(row) == want


def test_capped_at_70():
    # pending and sessions both print this inline; an uncapped description is a
    # 200-character row that wraps and destroys the column layout.
    assert len(name_of({"description": "x" * 300})) == 70

PREAMBLES = [
    "# AGENTS.md instructions\n\n<INSTRUCTIONS>\n<!-- AUTONOMY DIRECTIVE -->",
    "# AGENTS.md instructions for /opt/Code/github.com/x/y",
    "<recommended_plugins> Here is a list of plugins that are available",
    '<codex_internal_context source="goal"> Continue working towards',
    "<environment_context>\n  <cwd>/Users/beta</cwd>\n  <shell>zsh</shell>",
    "You have oh-my-codex installed. AGENTS.md is the orchestration brain",
]


@pytest.mark.parametrize("text", PREAMBLES)
def test_host_preambles_are_not_names(text):
    """1,126 of 1,750 codex sessions (64%) were named by injected text.

    A FIFTH shape only became visible after the first four were skipped:
    <environment_context> sits at user#2 and the real message at user#3.
    """
    assert name_of({"description": text}) == "(untitled)"


def test_a_title_still_wins_over_a_preamble():
    assert name_of({"title": "real name", "description": "<recommended_plugins> x"}) == "real name"


def test_only_a_message_that_begins_as_the_directive_is_one():
    # A human quoting the tag while debugging keeps their message as the name.
    assert name_of({"description": "why does <recommended_plugins> show up in my name?"}) \
        == "why does show up in my name?"


def test_a_pasted_image_tag_is_stripped():
    # The {1,40} scrubber cannot reach it — an image tag carries a long path.
    assert name_of({"description": '<image name=[Image #1] path="/var/f/x.png"> summarize the book'}) \
        == "summarize the book"


def test_real_messages_are_untouched_thai_included():
    assert name_of({"description": "no i just you read thor memory /mcp"}) \
        == "no i just you read thor memory /mcp"
    assert name_of({"description": "[drdo-oracle] deploy เสร็จแล้ว + แก้ความเข้าใจผิด"}) \
        == "[drdo-oracle] deploy เสร็จแล้ว + แก้ความเข้าใจผิด"
