"""nameOf is a cross-implementation contract. These are test/name-of.test.ts's cases.

The Python side shipped `title or description` while TypeScript promoted slash commands,
stripped compaction caveats and capped the length — so the same session was called
`/forward` by one reader and `"<local-command-caveat>Caveat: The messages below were
genera"` by the other, in `sessions` as well as `pending`. Nothing failed; they just
disagreed, which is the failure mode a second implementation exists to expose.
"""

import pytest

from relicpy.query import name_of

CASES = [
    ("a real title wins outright",
     {"title": "close-bank-sharding", "description": "anything at all"}, "close-bank-sharding"),
    ("a blank title falls through to the description",
     {"title": "   ", "description": "fix the tokenizer"}, "fix the tokenizer"),
    ("a slash command is promoted over its XML",
     {"description": "<command-name>/forward</command-name><command-args></command-args>"}, "/forward"),
    ("a slash command keeps its arguments",
     {"description": "<command-name>/rrr</command-name><command-args> --light </command-args>"}, "/rrr --light"),
    ("an unterminated caveat block is dropped, not displayed",
     {"description": "<local-command-caveat>Caveat: The messages below were generated by the user while"}, "(untitled)"),
    ("a bare caveat sentence is dropped too",
     {"description": "Caveat: The messages below were generated by the user while running local commands"}, "(untitled)"),
    ("stray short tags are scrubbed to spaces",
     {"description": "<system-reminder> index the vault </system-reminder>"}, "index the vault"),
    ("nothing usable is named, not left blank",
     {"description": ""}, "(untitled)"),
]


@pytest.mark.parametrize("what,row,want", CASES, ids=[c[0] for c in CASES])
def test_name_of(what, row, want):
    assert name_of(row) == want


def test_capped_at_70():
    # pending and sessions both print this inline; an uncapped description is a
    # 200-character row that wraps and destroys the column layout.
    assert len(name_of({"description": "x" * 300})) == 70
